### ISSUE TITLE
Mapping error when import data from magento 2

### ISSUE THREAD

**Issue by Abdoul19** [DivanteLtd/storefront-api#45]
Hi, maybe I'm doing something wrong, but I can't import data (only products) from magento 2 backend with the command : yarn mage2vs import
Elastc is throwing a mapping error as : 

llegal_argument_exception\",\"reason\":\"Rejecting mapping update to [vue_storefront_catalog] as the final mapping would have more than 1 type 

NB: this occur only with product import

**Comment by Abdoul19** [comment]
@ResuBaka, can you help me, please ?

**Comment by lnicorena** [comment]
Hey! I'm facing the same issue here. (running default installation of storefront-api with magento 2)

`"statusCode":400,"response":"{"error":{"root_cause":[
{"type":"remote_transport_exception","reason":"[712cb51e7aad][172.18.0.2:9300][indices:data/write/update[s]]"}],
"type":"illegal_argument_exception","reason":"Rejecting mapping update to [vue_storefront_catalog] as the final mapping would have more than 1 type: [category, product]"},"status":400}"},
    at /var/www/node_modules/mage2vuestorefront/src/adapters/nosql/elasticsearch.js:80:15,     
    at respond (/var/www/node_modules/elasticsearch/src/lib/transport.js:327:9),     
    at checkRespForFailure (/var/www/node_modules/elasticsearch/src/lib/transport.js:267:7),     
    at HttpConnector.<anonymous> (/var/www/node_modules/elasticsearch/src/lib/connectors/http.js:166:7),     
    at IncomingMessage.wrapper (/var/www/node_modules/lodash/lodash.js:4929:19),     
    at IncomingMessage.emit (events.js:203:15),     
    at endReadableNT (_stream_readable.js:1145:12),     
    at process._tickCallback (internal/process/next_tick.js:63:19)]
`

**Comment by pkarw** [comment]
If you're using mage2vsbridge indexer you need to change the elasticsearch version in the config.js setting `7.1`

**Comment by one1note** [comment]
I'm also facing the same issue, the elasticsearch version in the config.js was already set to 7.1.
